spring:
  datasource:
    app:
      jdbc-url: jdbc:postgresql://postgres:5432/orderflow?currentSchema=app_schema
      username: orderflow_user
      password: orderflow_pass
      driver-class-name: org.postgresql.Driver
    flowable:
      jdbc-url: jdbc:postgresql://postgres:5432/orderflow?currentSchema=flowable_schema
      username: orderflow_user
      password: orderflow_pass
      driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: app_schema
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: app_schema
    baseline-on-migrate: true
    baseline-version: 0

flowable:
  database-schema-update: true
  database-schema: flowable_schema
  async-executor-activate: true
  process-definition-cache-limit: 100

logging:
  level:
    root: INFO
    org.flowable: INFO
    com.orderflow: INFO
    org.hibernate.SQL: INFO
